### ISSUE TITLE
css选择器

### ISSUE THREAD

**Issue by PLDaily** [PLDaily/blog#47]
## child选择器
```css
.parent p:first-child {
	color:green;
}
.parent p:last-child {
	color: red;
}
.parent p:nth-child(1) {
	color:yellow;
}
.parent p:nth-last-child(1) {
	color:blue;
}
```
* :first-child: parent类中所有p的父元素中p作为第一个子元素时字体颜色为绿色
* :last-child: parent类中所有p的父元素中p作为最后一个子元素时字体颜色为红色
* :nth-child(n): parent类中所有p的父元素中p作为第n个子元素时字体颜色为黄色
* :nth-last-child(1): parent类中所有p的父元素中p作为倒数n个子元素时字体颜色为蓝色

## type选择器
```css
.parent p:first-of-type {
	color:green;
}
.parent p:last-of-type {
	color:red;
}
.parent p:nth-of-type(2) {
	color:yellow;
}
.parent p:nth-last-of-type(2) {
	color:blue;
}
```

* :first-of-type: parent类中所有p的父元素中第一个标签为p的子元素的字体颜色为绿色
* :last-of-type: parent类中所有p的父元素中最后一个标签为p的子元素的字体颜色为红色
* :nth-of-type(n): parent类中所有p的父元素中第n个标签为p的子元素的字体颜色为黄色
* :nth-last-of-type(n): parent类中所有p的父元素中倒数第n个标签为p的子元素的字体颜色为蓝色

## not选择器
```css
.parent p:not(.first) {
	color: red;
}
```
* :not(): parent类中class类名不为first的p元素的字体颜色为红色

## 注意事项

* 以上选择均为parent类中的所有子元素(包括子元素的子元素)，如果只想获取到一级子元素(即不包括子元素的子元素)，则使用">"。
示例：
```css
.parent > p:first-child {
	color: red;
}
```
